#!/usr/bin/env bash

MAXLATENCY=200

for ((k=51;k<80;k+=2))
do
    i=$(bc <<<"scale=2; $k / 100" )
    i="0"$i
    ./rungarnet 16 4 1 HierarchicalRing $i uniform_random 20000
    LATENCY=$(<m5out/latest_latency.txt)
done


