#!/usr/bin/zsh

mn=$(echo 1.05)
while [ 1 -eq 1 ]; do
    load=$(awk '{print $1}'< /proc/loadavg)
    if (($load < $mn)); then
        ./rundsent /home/dav/gem5/m5out/aaa/1024core/Mesh_XY-1024core-16x16-4cpus_per_router-uniform_random-0.03injrate-20000cycles
        ./rundsent /home/dav/gem5/m5out/aaa/1024core/Mesh_XY-1024core-32x32-uniform_random-0.01injrate-20000cycles
        ./rundsent /home/dav/gem5/m5out/aaa/1024core/FlattenedButterfly-1024core-32x32-uniform_random-0.17injrate-10000cycles
        break
    fi
    sleep 10
done
