#!/usr/bin/env bash

MAXLATENCY=400

EXTRA=4
for ((k=1;k<95;k+=2))
do
    i=$(bc <<<"scale=2; $k / 100" )
    i="0"$i
    ./rungarnet 64 4 2 Mesh_XY $i uniform_random 20000
    LATENCY=$(<m5out/latest_latency.txt)
    if [ $LATENCY -gt $MAXLATENCY ]; then
        EXTRA=$(($EXTRA - 1))
    fi
    if [ $EXTRA -eq 0 ]; then
        break
    fi
done

EXTRA=4
for ((k=1;k<95;k+=2))
do
    i=$(bc <<<"scale=2; $k / 100" )
    i="0"$i
    ./rungarnet 64 8 2 Mesh_XY $i uniform_random 20000
    LATENCY=$(<m5out/latest_latency.txt)
    if [ $LATENCY -gt $MAXLATENCY ]; then
        EXTRA=$(($EXTRA - 1))
    fi
    if [ $EXTRA -eq 0 ]; then
        break
    fi
done



EXTRA=5
for ((k=1;k<95;k+=2))
do
    i=$(bc <<<"scale=2; $k / 100" )
    i="0"$i
    ./rungarnet 32 4 2 HierarchicalRing $i uniform_random 20000
    LATENCY=$(<m5out/latest_latency.txt)
    if [ $LATENCY -gt $MAXLATENCY ]; then
        EXTRA=$(($EXTRA - 1))
    fi
    if [ $EXTRA -eq 0 ]; then
        break
    fi
done

EXTRA=5
for ((k=1;k<95;k+=2))
do
    i=$(bc <<<"scale=2; $k / 100" )
    i="0"$i
    ./rungarnet 64 4 2 HierarchicalRing $i uniform_random 20000
    LATENCY=$(<m5out/latest_latency.txt)
    if [ $LATENCY -gt $MAXLATENCY ]; then
        EXTRA=$(($EXTRA - 1))
    fi
    if [ $EXTRA -eq 0 ]; then
        break
    fi
done

EXTRA=5
for ((k=1;k<95;k+=2))
do
    i=$(bc <<<"scale=2; $k / 100" )
    i="0"$i
    ./rungarnet 64 4 4 HierarchicalRing $i uniform_random 20000
    LATENCY=$(<m5out/latest_latency.txt)
    if [ $LATENCY -gt $MAXLATENCY ]; then
        EXTRA=$(($EXTRA - 1))
    fi
    if [ $EXTRA -eq 0 ]; then
        break
    fi
done
