#!/usr/bin/env bash

MAXLATENCY=500


for ((k=19;k<95;k+=4))
do
    i=$(bc <<<"scale=2; $k / 100" )
    i="0"$i
    ./rungarnet 256 8 4 FlattenedButterfly $i uniform_random 20000
    LATENCY=$(<m5out/latest_latency.txt)
    if [ $LATENCY -gt $MAXLATENCY ]; then
        break
    fi
done
