#!/usr/bin/env bash

MAXLATENCY=300

EXTRA=2
for ((k=8;k<95;k+=4))
do
    i=$(bc <<<"scale=2; $k / 100" )
    i="0"$i
    ./rungarnet 16 4 1 HierarchicalRing $i uniform_random 100000
    LATENCY=$(<m5out/latest_latency.txt)
    if [ $LATENCY -gt $MAXLATENCY ]; then
        EXTRA=$(($EXTRA - 1))
    fi
    if [ $EXTRA -eq 0 ]; then
        break
    fi
done


