#!/usr/bin/env bash

MAXLATENCY=300

for ((k=3;k<95;k+=2))
do
    i=$(bc <<<"scale=2; $k / 100" )
    i="0"$i
    ./rungarnet 1024 16 4 Mesh_XY $i uniform_random 20000
    LATENCY=$(<m5out/latest_latency.txt)
    if [ $LATENCY -gt $MAXLATENCY ]; then
        break
    fi
done

