#!/usr/bin/zsh

mn=$(echo 1.0)
while [ 1 -eq 1 ]; do
    load=$(awk '{print $1}'< /proc/loadavg)
    if (($load < $mn)); then
        ./rungarnet 128 4 8 Mesh_XY 0.01 uniform_random 20000
        ./rungarnet 128 4 8 Mesh_XY 0.05 uniform_random 20000
        ./rungarnet 128 4 8 Mesh_XY 0.09 uniform_random 20000
        ./rungarnet 128 4 8 Mesh_XY 0.11 uniform_random 20000
        ./rungarnet 128 4 8 Mesh_XY 0.15 uniform_random 20000
        ./rungarnet 256 4 8 Mesh_XY 0.01 uniform_random 20000
        ./rungarnet 256 4 8 Mesh_XY 0.03 uniform_random 20000
        ./rungarnet 256 4 8 Mesh_XY 0.05 uniform_random 20000
        ./rungarnet 256 4 8 Mesh_XY 0.07 uniform_random 20000
        ./rungarnet 512 8 8 Mesh_XY 0.01 uniform_random 20000
        ./rungarnet 512 8 8 Mesh_XY 0.03 uniform_random 20000
        ./rungarnet 512 8 8 Mesh_XY 0.05 uniform_random 20000
        ./rungarnet 512 8 8 Mesh_XY 0.07 uniform_random 20000
        ./rungarnet 512 8 8 Mesh_XY 0.11 uniform_random 20000
        ./rungarnet 256 4 8 Mesh_XY 0.11 uniform_random 20000
        break
    fi
    sleep 10
done

