#!/usr/bin/env bash

MAXLATENCY=200

for ((k=1;k<40;k+=2))
do
    i=$(bc <<<"scale=2; $k / 100" )
    i="0"$i
    ./rungarnet 16 2 2 Ring $i uniform_random 20000
done

for ((k=1;k<40;k+=2))
do
    i=$(bc <<<"scale=2; $k / 100" )
    i="0"$i
    ./rungarnet 32 2 2 Ring $i uniform_random 20000
done

