#!/usr/bin/env bash

./r 64 8 Mesh_XY 0.9 0 uniform_random
./r 64 8 Mesh_XY 0.9 1 uniform_random
./r 64 8 Mesh_XY 0.9 2 uniform_random
./r 64 8 Mesh_XY 0.9 0 tornado
./r 64 8 Mesh_XY 0.9 1 tornado
./r 64 8 Mesh_XY 0.9 2 tornado
./r 64 8 Mesh_XY 0.9 0 shuffle
./r 64 8 Mesh_XY 0.9 1 shuffle
./r 64 8 Mesh_XY 0.9 2 shuffle
./r 64 8 Mesh_XY 0.9 0 bit_rotation
./r 64 8 Mesh_XY 0.9 1 bit_rotation
./r 64 8 Mesh_XY 0.9 2 bit_rotation
